export const industrialLands = [
  {
    id: "IND-001",
    name: "Rajiv Gandhi Industrial Estate",
    location: "Sector 14, Gurgaon",
    area: "12.5 acres",
    owner: "Sharma Industries Pvt Ltd",
    status: "alert" as const,
    lastScan: "2026-02-12T09:30:00",
    coordinates: { lat: 28.4595, lng: 77.0266 },
    boundaryChange: 2.3,
  },
  {
    id: "IND-002",
    name: "MIDC Industrial Zone B",
    location: "Bhosari, Pune",
    area: "8.2 acres",
    owner: "Pune Steel Works",
    status: "safe" as const,
    lastScan: "2026-02-12T10:15:00",
    coordinates: { lat: 18.6298, lng: 73.8474 },
    boundaryChange: 0,
  },
  {
    id: "IND-003",
    name: "SEZ Plot 47-A",
    location: "Noida Phase II",
    area: "15.0 acres",
    owner: "National Textiles Corp",
    status: "warning" as const,
    lastScan: "2026-02-12T08:45:00",
    coordinates: { lat: 28.5355, lng: 77.391 },
    boundaryChange: 0.8,
  },
  {
    id: "IND-004",
    name: "Govandi Industrial Area",
    location: "Govandi East, Mumbai",
    area: "6.7 acres",
    owner: "Mumbai Chemical Industries",
    status: "safe" as const,
    lastScan: "2026-02-12T11:00:00",
    coordinates: { lat: 19.0596, lng: 72.9133 },
    boundaryChange: 0,
  },
  {
    id: "IND-005",
    name: "Whitefield Tech Park",
    location: "Whitefield, Bangalore",
    area: "20.1 acres",
    owner: "Bangalore IT Holdings",
    status: "alert" as const,
    lastScan: "2026-02-11T16:20:00",
    coordinates: { lat: 12.9698, lng: 77.7499 },
    boundaryChange: 3.1,
  },
  {
    id: "IND-006",
    name: "Salt Lake Industrial Block",
    location: "Salt Lake, Kolkata",
    area: "9.4 acres",
    owner: "Bengal Manufacturing Ltd",
    status: "safe" as const,
    lastScan: "2026-02-12T07:30:00",
    coordinates: { lat: 22.5803, lng: 88.4169 },
    boundaryChange: 0,
  },
]

export const alerts = [
  {
    id: "ALT-001",
    landId: "IND-001",
    landName: "Rajiv Gandhi Industrial Estate",
    type: "encroachment" as const,
    severity: "high" as const,
    date: "2026-02-12T09:30:00",
    description:
      "Unauthorized construction detected on southern boundary. Estimated 2.3% encroachment into industrial plot area.",
    resolved: false,
  },
  {
    id: "ALT-002",
    landId: "IND-005",
    landName: "Whitefield Tech Park",
    type: "encroachment" as const,
    severity: "critical" as const,
    date: "2026-02-11T16:20:00",
    description:
      "Major boundary violation on eastern perimeter. New structure extends 3.1% into designated tech park land.",
    resolved: false,
  },
  {
    id: "ALT-003",
    landId: "IND-003",
    landName: "SEZ Plot 47-A",
    type: "boundary_shift" as const,
    severity: "medium" as const,
    date: "2026-02-12T08:45:00",
    description:
      "Potential fence realignment detected on north-west corner. 0.8% variation observed from recorded boundary.",
    resolved: false,
  },
  {
    id: "ALT-004",
    landId: "IND-001",
    landName: "Rajiv Gandhi Industrial Estate",
    type: "vegetation" as const,
    severity: "low" as const,
    date: "2026-02-10T14:00:00",
    description:
      "Dense vegetation growth detected along western boundary making visual monitoring difficult.",
    resolved: true,
  },
  {
    id: "ALT-005",
    landId: "IND-002",
    landName: "MIDC Industrial Zone B",
    type: "boundary_shift" as const,
    severity: "low" as const,
    date: "2026-02-09T11:30:00",
    description:
      "Minor discrepancy in boundary markers on north side. Likely due to soil erosion. No encroachment detected.",
    resolved: true,
  },
]

export const scanHistory = [
  {
    id: "SCN-001",
    date: "2026-02-12T09:30:00",
    type: "Satellite Scan",
    status: "completed" as const,
    findings: "Boundary anomaly detected - southern perimeter",
  },
  {
    id: "SCN-002",
    date: "2026-02-11T09:30:00",
    type: "Drone Survey",
    status: "completed" as const,
    findings: "All boundaries intact, no changes detected",
  },
  {
    id: "SCN-003",
    date: "2026-02-10T09:30:00",
    type: "Satellite Scan",
    status: "completed" as const,
    findings: "Vegetation obstruction on western boundary",
  },
  {
    id: "SCN-004",
    date: "2026-02-09T09:30:00",
    type: "Satellite Scan",
    status: "completed" as const,
    findings: "No anomalies detected",
  },
  {
    id: "SCN-005",
    date: "2026-02-08T09:30:00",
    type: "Drone Survey",
    status: "completed" as const,
    findings: "Boundary markers verified, all within tolerance",
  },
  {
    id: "SCN-006",
    date: "2026-02-07T09:30:00",
    type: "Satellite Scan",
    status: "completed" as const,
    findings: "No anomalies detected",
  },
]

export const documents = [
  {
    id: "DOC-001",
    name: "Land Title Deed - IND-001",
    type: "title_deed" as const,
    uploadedBy: "Sharma Industries Pvt Ltd",
    date: "2025-08-15",
    status: "verified" as const,
  },
  {
    id: "DOC-002",
    name: "Construction Permit - Extension",
    type: "permit" as const,
    uploadedBy: "Sharma Industries Pvt Ltd",
    date: "2025-11-20",
    status: "pending" as const,
  },
  {
    id: "DOC-003",
    name: "Environmental Clearance Certificate",
    type: "clearance" as const,
    uploadedBy: "Bangalore IT Holdings",
    date: "2025-06-10",
    status: "verified" as const,
  },
  {
    id: "DOC-004",
    name: "Boundary Survey Report - 2025",
    type: "survey" as const,
    uploadedBy: "Government Surveyor",
    date: "2025-09-01",
    status: "verified" as const,
  },
  {
    id: "DOC-005",
    name: "Expansion Application - Plot 47-A",
    type: "permit" as const,
    uploadedBy: "National Textiles Corp",
    date: "2026-01-15",
    status: "rejected" as const,
  },
]
